name: Tests

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        node-version: [ '14' ]

    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: |
            package.json
            yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn run build

      - name: Verify package build
        run: ls -alF htdocs/static/assets/*.bundle.js
